language: objective-c
osx_image:
  xcode7.3
  xcode8
sudo: false
before_install:
  brew install carthage

script: ./Scripts/build.sh

branches:
  only:
    - master

env:
- TARGET=WebDriverAgentLib SDK=iphonesimulator ACTION=test
- TARGET=WebDriverAgentRunner SDK=iphonesimulator ACTION=build
- TARGET=WebDriverAgentRunner SDK=iphoneos ACTION=build
- TARGET=WebDriverAgentUSBClient SDK=macosx ACTION=build
