language: objective-c
osx_image: xcode7.3
sudo: false
before_install:
  - brew install carthage
  - gem install xcpretty-travis-formatter

script: ./Scripts/build.sh

branches:
  only:
    - master

env:
- TARGET=WebDriverAgentLib SDK=iphonesimulator DESTINATION='iPad 2' ACTION=test
- TARGET=WebDriverAgentLib SDK=iphonesimulator DESTINATION='iPhone 6' ACTION=test
- TARGET=WebDriverAgentRunner SDK=iphonesimulator ACTION=build
- TARGET=WebDriverAgentRunner SDK=iphoneos ACTION=build
- TARGET=WebDriverAgentUSBClient SDK=macosx ACTION=build
