language: objective-c
osx_image: xcode9.2
sudo: false

cache:
  directories:
  - Carthage
  - Inspector/node_modules

script: ./Scripts/build.sh

branches:
  only:
    - master

env:
# Builds
- PLATFORM=ios ACTION=build TARGET=runner SDK=sim
- PLATFORM=ios ACTION=build TARGET=runner SDK=device
- PLATFORM=tvos ACTION=build TARGET=runner SDK=sim
- PLATFORM=tvos ACTION=build TARGET=runner SDK=device

# Analyze
- PLATFORM=ios ACTION=analyze TARGET=lib SDK=sim
- PLATFORM=ios ACTION=analyze TARGET=runner SDK=sim
- PLATFORM=tvos ACTION=analyze TARGET=lib SDK=sim
- PLATFORM=tvos ACTION=analyze TARGET=runner SDK=sim

# Unit tests
- PLATFORM=ios ACTION=unit_test DEST=iphone TARGET=lib SDK=sim
- PLATFORM=ios ACTION=unit_test DEST=ipad TARGET=lib SDK=sim
- PLATFORM=tvos ACTION=unit_test DEST=atv TARGET=lib SDK=sim

# Integration tests iPhone
- PLATFORM=ios ACTION=int_test_1 DEST=iphone TARGET=lib SDK=sim
- PLATFORM=ios ACTION=int_test_2 DEST=iphone TARGET=lib SDK=sim
- PLATFORM=ios ACTION=int_test_3 DEST=iphone TARGET=lib SDK=sim

# Integration tests iPad
- PLATFORM=ios ACTION=int_test_1 DEST=ipad TARGET=lib SDK=sim
- PLATFORM=ios ACTION=int_test_2 DEST=ipad TARGET=lib SDK=sim
- PLATFORM=ios ACTION=int_test_3 DEST=ipad TARGET=lib SDK=sim

# Integration tests Apple TV
- PLATFORM=tvos ACTION=int_test_1 DEST=atv TARGET=lib SDK=sim
- PLATFORM=tvos ACTION=int_test_2 DEST=atv TARGET=lib SDK=sim