language: objective-c
osx_image: xcode7.1
before_install:
  brew install carthage

script: ./Scripts/build.sh

branches:
  only:
    - master

env:
- PROJECT=WebDriverAgent.xcodeproj TARGET=WebDriverAgentRunner SDK=iphonesimulator ACTION=build-tests
- PROJECT=WebDriverAgent.xcodeproj TARGET=WebDriverAgentRunner SDK=iphoneos ACTION=build-tests
- PROJECT=UIAWebDriverAgent/WebDriverAgent.xcodeproj TARGET=WebDriverAgent SDK=iphonesimulator ACTION=build
