language: objective-c
osx_image: xcode8.1
sudo: false

cache:
  directories:
  - Carthage
  - Inspector/node_modules

script: ./Scripts/build.sh

branches:
  only:
    - master

env:
- TARGET=WebDriverAgentLib SDK=iphonesimulator ACTION=test DESTINATION='iPad Air 2' IOS='10.1'
- TARGET=WebDriverAgentLib SDK=iphonesimulator ACTION=test DESTINATION='iPhone SE' IOS='10.1'
- TARGET=WebDriverAgentRunner SDK=iphonesimulator ACTION=build
- TARGET=WebDriverAgentRunner SDK=iphoneos ACTION=build
